CREATE DATABASE catalogue_formation;

CREATE TABLE  `catalogue_formation`.`theme` (
`ID_THEME` INT( 11 ) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
`NOM` VARCHAR( 255 ) NOT NULL ,
`DESC` TEXT NOT NULL
) ENGINE = MYISAM ;

CREATE TABLE  `catalogue_formation`.`session` (
`ID_SESSION` INT( 11 ) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`DATE_DEBUT` DATE NOT NULL ,
`DATE_FIN` DATE NOT NULL ,
`FORMATION` INT( 11 ) NOT NULL
) ENGINE = MYISAM ;

CREATE TABLE  `catalogue_formation`.`intervenant` (
`ID_INTERVENANT` INT( 11 ) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`NOM` VARCHAR( 255 ) NOT NULL ,
`PRENOM` VARCHAR( 255 ) NOT NULL ,
`EMAIL` VARCHAR( 255 ) NOT NULL ,
`METIER` VARCHAR( 255 ) NOT NULL ,
`ETABLISSEMENT` VARCHAR( 255 ) NOT NULL
) ENGINE = MYISAM ;

CREATE TABLE  `catalogue_formation`.`formation` (
`ID_FORMATION` INT( 11 ) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`NOM` VARCHAR( 255 ) NOT NULL ,
`OBJECTIF` TEXT NOT NULL ,
`PROGRAMME` TEXT NOT NULL ,
`INTERVENANT` INT( 11 ) UNSIGNED NOT NULL ,
`PREREQUIS` TEXT NOT NULL ,
`DUREE` VARCHAR( 255 ) NOT NULL ,
`LIEU` VARCHAR( 255 ) NOT NULL ,
`NIVCOMP` SMALLINT( 2 ) UNSIGNED NOT NULL ,
`THEME` INT( 11 ) NOT NULL
) ENGINE = MYISAM ;

CREATE TABLE  `catalogue_formation`.`tarif` (
`ID_TARIF` INT( 11 ) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`NIVCOMP` INT( 11 ) UNSIGNED NOT NULL ,
`STATUS` INT( 11 ) UNSIGNED NOT NULL ,
`PRIX` INT( 11 ) UNSIGNED NOT NULL
) ENGINE = MYISAM ;

CREATE TABLE  `catalogue_formation`.`nivcomp` (
`ID_NIVCOMP` SMALLINT( 2 ) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`NOM` VARCHAR( 20 ) NOT NULL
) ENGINE = MYISAM ;

CREATE TABLE  `catalogue_formation`.`status` (
`ID_STATUS` INT( 11 ) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`NOM` VARCHAR( 255 ) NOT NULL
) ENGINE = MYISAM ;

CREATE TABLE  `catalogue_formation`.`utilisateur` (
`ID_UTILISATEUR` INT( 11 ) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`NOM` VARCHAR( 255 ) NOT NULL ,
`PRENOM` VARCHAR( 255 ) NOT NULL ,
`EMAIL` VARCHAR( 255 ) NOT NULL ,
`STATUS` INT( 11 ) UNSIGNED NOT NULL ,
`DATEINSCRIPT` DATE NOT NULL
) ENGINE = MYISAM ;

INSERT INTO `catalogue_formation`.`nivcomp` (ID_NIVCOMP, NOM) VALUES (1, 'Généraliste');
INSERT INTO `catalogue_formation`.`nivcomp` (ID_NIVCOMP, NOM) VALUES (2, 'Pratique');
INSERT INTO `catalogue_formation`.`nivcomp` (ID_NIVCOMP, NOM) VALUES (3, 'Scientifique');